steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-r', 'assets/*', 'gs://static-website-bucket-fd']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'cypress-test', '.']
- name: 'docker'
  args: ['run', 'cypress-test']